version: '3'

services:
  app:
    build: 
      context: ./node
    container_name: app
    networks: 
      - node-network
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root    
    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - node-network
    depends_on:
      - app
    volumes:
      - ./node:/usr/src/app

networks:
  node-network:
    driver: bridge
